# Generated by Django 4.0.2 on 2022-05-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
